Odświeżenie informacji z podstaw pandasa i numpy

1. Zaimportuj pakiety pandas, numpy i matplotlib

In [1]:
import numpy as np
import pandas as pd

## Numpy

1. Stwórz dziesięcioelementowy wektor składający się wyłącznie z samych zer 

In [3]:
# np.array([0] * 10)
# np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

2. Stwórz sześcioelementowy wektor składający się z samych jedynek, i zastąp drugi element wartością 4

In [5]:
wektor = np.ones(6)
wektor[1] = 4
wektor

array([1., 4., 1., 1., 1., 1.])

3. Stwórz wektor z wartościami od 1 do 15

In [8]:
wektor2 = np.arange(1, 16)
wektor2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

4. Odwróć kolejność wektora z zad 3.

In [12]:
# np.flip(wektor2)
# wektor2[::-1]

In [13]:
text = 'lubieSAD'
text[::-1]

'DASeibul'

5. Stwórz macierz wartości losowych o wymiarze 10 wierszy x 10 kolumn

In [14]:
macierz = np.random.rand(10, 10)
macierz

array([[0.7104279 , 0.64905796, 0.73764742, 0.36530306, 0.40114889,
        0.75714587, 0.65703398, 0.0399723 , 0.13974331, 0.31698949],
       [0.86303696, 0.60307302, 0.36053829, 0.02261983, 0.53971593,
        0.66052508, 0.35388766, 0.07142887, 0.88942096, 0.5353342 ],
       [0.58289536, 0.4238141 , 0.06218773, 0.71243084, 0.70469255,
        0.29261254, 0.76630309, 0.93372781, 0.78866341, 0.60018677],
       [0.53630587, 0.41604324, 0.31353979, 0.43267317, 0.06758496,
        0.54264283, 0.48316796, 0.49855808, 0.45032099, 0.10338618],
       [0.2898574 , 0.45652586, 0.5612976 , 0.33268794, 0.86651123,
        0.53250701, 0.79395247, 0.27313924, 0.28814555, 0.94654416],
       [0.41775954, 0.25508228, 0.89925964, 0.26295378, 0.43542211,
        0.65473767, 0.56414182, 0.24864956, 0.94350388, 0.10281246],
       [0.01550635, 0.89696945, 0.13120271, 0.71663245, 0.75110785,
        0.2393746 , 0.50922708, 0.73336418, 0.14492561, 0.37282313],
       [0.97314437, 0.13907775, 0.7826689

6. Jakim wyrażeniem sprawdzisz wymiary macierzy?

In [15]:
macierz.shape

(10, 10)

7. Stwórz macierz 6x6, wypełnij ją zerami, a diagonalną wypełnij liczbami od 1 do 6

In [19]:
macierz_zer = np.zeros((6, 6))
macierz_zer

wektor16 = np.arange(1,7)
wektor16

np.fill_diagonal(macierz_zer, wektor16)
macierz_zer

np.diag(wektor16)

macierz_zer = np.zeros((6,6))
macierz_zer

macierz_zer[np.diag_indices_from(macierz_zer)] = wektor16
macierz_zer

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

8. Stwórz losową macierz o wielkości 8x4, i następnie zestandaryzuj jej kolumny (dla każdej zmiennej, dla każdej jej wartości odejmij wartość średnią, i podziel przez odchylenie standardowe)

In [36]:
macierz = np.random.rand(8, 4)
macierz

array([[0.12518313, 0.14647605, 0.32492029, 0.55174204],
       [0.80626394, 0.94066744, 0.90837184, 0.11853153],
       [0.17399944, 0.90002852, 0.99917525, 0.97921747],
       [0.51967563, 0.3559622 , 0.91695633, 0.35059482],
       [0.63788494, 0.10636902, 0.25525268, 0.79011573],
       [0.11546911, 0.26918279, 0.55301273, 0.63717352],
       [0.83452324, 0.30984203, 0.79626906, 0.21247084],
       [0.37215559, 0.49810481, 0.15482857, 0.94569446]])

In [41]:
srednie = np.mean(macierz, axis=0) # 0 to kolumna, 1 to wiersz
odchylenia = np.std(macierz, axis=0)

In [ ]:
(macierz - srednie) / odchylenia

9. Z losowej macierzy 6x6:
    * wskaż element największy i jego indeks
    * wskaż element najmniejszy i jego indeks

In [74]:
macierz_random = np.random.rand(6, 6)

In [78]:
macierz_random.max()
np.max(macierz_random)

0.9965228394564889

In [83]:
np.unravel_index(macierz_random.argmax(), macierz_random.shape)

(2, 5)

In [86]:
np.where(macierz_random == macierz_random.max())

(array([2], dtype=int64), array([5], dtype=int64))

In [89]:
np.where(macierz_random == macierz_random.min())

(array([5], dtype=int64), array([4], dtype=int64))

10. Wszytkie elementy z wektora [1,0,2,3,4,0,2,0,0,2,0] będące powyżej zera, zastąp jedynką

In [94]:
wektor = np.array([1,0,2,3,4,0,2,0,0,2,0])
wektor[wektor > 0] = 1
wektor

array([1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0])

11. Znajdź niezerowe elementy wektora [0,0,1,2,0,1,13,0,-1].

In [98]:
wektor2 = np.array([0,0,1,2,0,1,13,0,-1])
wektor2 != 0
print(wektor2[np.nonzero(wektor2)])

[ 1  2  1 13 -1]


12. Stwórz losowy wektor 40-elementowy i znajdź jego średnią, medianę, odchylenie standardowe, pierwszy decyl, dziewiąty decyl, kwartyl1 i kwartyl3

In [100]:
wektor = np.random.rand(40)
wektor

array([0.15455981, 0.09649445, 0.15771663, 0.73387685, 0.80367719,
       0.56324427, 0.00419376, 0.537219  , 0.12729846, 0.58870221,
       0.41106774, 0.36207606, 0.84501397, 0.80687251, 0.3039614 ,
       0.7012263 , 0.12767901, 0.55020133, 0.83310729, 0.01996818,
       0.08698258, 0.45909508, 0.48767588, 0.43540605, 0.79392314,
       0.05183681, 0.41363209, 0.5895996 , 0.81527398, 0.99657182,
       0.32042087, 0.12702154, 0.9238243 , 0.74079754, 0.57180782,
       0.76233849, 0.66590954, 0.3880994 , 0.65273001, 0.13885731])

In [101]:
np.mean(wektor)

0.4787490073338718

In [108]:
np.median(wektor)

0.5124474393963017

In [110]:
np.std(wektor)

0.28415552301180613

In [111]:
np.percentile(wektor, 25) # kwartyl1

0.1569274290005465

In [113]:
np.percentile(wektor, 75) # kwartyl3

0.735607021496511

In [114]:
np.percentile(wektor, [10, 90]) # pierwszy decyl i dziesiąty decyl

array([0.09554327, 0.81705731])

13. Posortuj powyższy wektor

In [117]:
wektor.sort()
wektor

array([0.00419376, 0.01996818, 0.05183681, 0.08698258, 0.09649445,
       0.12702154, 0.12729846, 0.12767901, 0.13885731, 0.15455981,
       0.15771663, 0.3039614 , 0.32042087, 0.36207606, 0.3880994 ,
       0.41106774, 0.41363209, 0.43540605, 0.45909508, 0.48767588,
       0.537219  , 0.55020133, 0.56324427, 0.57180782, 0.58870221,
       0.5895996 , 0.65273001, 0.66590954, 0.7012263 , 0.73387685,
       0.74079754, 0.76233849, 0.79392314, 0.80367719, 0.80687251,
       0.81527398, 0.83310729, 0.84501397, 0.9238243 , 0.99657182])

14. Stwórz 10-elementowy wektor z wartościami od 0 do 1, mającymi równe odstępy

In [118]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Pandas

Będziemy pracować na ramce danych (pandas.DataFrame):

In [120]:
dane = {
    'gender': ['m'] * 5 + ['f'] * 5,
    'age': [23, 24, 25, 28, 32, 54, 21, np.nan, 45, np.nan],
    'earnings': [2500, np.nan, 2700, 3400, 2500, 2900, 4300, 3400, 3250, 1100]
}
indeks = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

16. Stwórz ramkę danych, w której dane będą zasilone słownikiem 'dane', a indeksy wierszy to lista 'indeks'

In [121]:
ramka = pd.DataFrame(dane, indeks)
ramka

gender   age  earnings
a      m  23.0    2500.0
b      m  24.0       NaN
c      m  25.0    2700.0
d      m  28.0    3400.0
e      m  32.0    2500.0
f      f  54.0    2900.0
g      f  21.0    4300.0
h      f   NaN    3400.0
i      f  45.0    3250.0
j      f   NaN    1100.0

17. Wyświetl typy zmiennych w ramce

In [124]:
ramka.dtypes
ramka.info()

gender       object
age         float64
earnings    float64
dtype: object

18. Wyświetl podstawowe statystyki opisowe za pomocą odpowiedniej metody

In [136]:
ramka.describe()

age     earnings
count   8.000000     9.000000
mean   31.500000  2894.444444
std    11.844227   879.077800
min    21.000000  1100.000000
25%    23.750000  2500.000000
50%    26.500000  2900.000000
75%    35.250000  3400.000000
max    54.000000  4300.000000

19. Wyświetl pierwsze dwie obserwacje z ramki (dwoma sposobami)

In [139]:
ramka.iloc[0:2, :]
#ramka.head(2)

gender   age  earnings
a      m  23.0    2500.0
b      m  24.0       NaN

20. Wyświetl trzy ostatnie obserwacje z podanej ramki (dwoma sposobami)

In [131]:
# ramka.tail(3)
# ramka[-3:, :]

gender   age  earnings
h      f   NaN    3400.0
i      f  45.0    3250.0
j      f   NaN    1100.0

21. Wyświetl kolumnę 'age' i 'earnings' 

In [142]:
# ramka[['age','earnings']]
ramka.loc[:, ['age', 'earnings']]

age  earnings
a  23.0    2500.0
b  24.0       NaN
c  25.0    2700.0
d  28.0    3400.0
e  32.0    2500.0
f  54.0    2900.0
g  21.0    4300.0
h   NaN    3400.0
i  45.0    3250.0
j   NaN    1100.0

22. Wyświetl ramkę zawierającą obserwacje nr 1,3,5 z kolumn 'gender' i 'earnings'

In [145]:
ramka.iloc[[1, 3, 5], :].loc[:, ['gender', 'earnings']] 

gender  earnings
b      m       NaN
d      m    3400.0
f      f    2900.0

23. Wyświetl obserwacje, w których zarobki są niższe od 3000

24. Wyświetl obserwacje, w których znajdują się  braki danych

In [154]:
ramka[ramka.isna().any(axis=1)]

gender   age  earnings
b      m  24.0       NaN
h      f   NaN    3400.0
j      f   NaN    1100.0

25. Wyświetl obserwacje, w których nie znajdują się żadne braki danych

In [156]:
ramka[~ramka.isna().any(axis=1)]

gender   age  earnings
a      m  23.0    2500.0
c      m  25.0    2700.0
d      m  28.0    3400.0
e      m  32.0    2500.0
f      f  54.0    2900.0
g      f  21.0    4300.0
i      f  45.0    3250.0

26. Wyświetl obserwacje, gdzie wiek jest niższy od 30, zarobki wyższe od 3000

In [158]:
ramka[(ramka['age'] < 30) & (ramka['earnings'] > 3000)]

# more inspiration for SQL-like queries: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.query.html 

gender   age  earnings
d      m  28.0    3400.0
g      f  21.0    4300.0

27. Wyświetl obserwacje, w których wiek znajduje się w przedziale [20;25]

In [160]:
ramka[ramka['age'].between(20, 25)]

gender   age  earnings
a      m  23.0    2500.0
b      m  24.0       NaN
c      m  25.0    2700.0
g      f  21.0    4300.0

28. Dodaj nowy wiersz o indeksie 'k' ['f',28, 3300]

In [164]:
ramka.loc['k'] = ['f',28, 3300]
ramka.loc['k']

gender         f
age           28
earnings    3300
Name: k, dtype: object

29. Usuń wiersz 'j' z ramki

In [168]:
ramka = ramka.drop('j')
ramka

gender   age  earnings
a      m  23.0    2500.0
b      m  24.0       NaN
c      m  25.0    2700.0
d      m  28.0    3400.0
e      m  32.0    2500.0
f      f  54.0    2900.0
g      f  21.0    4300.0
h      f   NaN    3400.0
i      f  45.0    3250.0
k      f  28.0    3300.0

30. Oblicz średnie wynagrodzenie w tym zbiorze

In [ ]:
np.loc

31. Oblicz średnie wynagrodzenie wg płci

32. Posortuj ramkę względem wieku malejąco

33. Zamień w pierwszej kolumnie wszystkie wartości 'f' na 'female', a 'm' na 'male'

34. Wskaż ile jest osób z podziałem na płeć w tym zbiorze

35. Dla każdej płci wskaż średnie zarobki, i średni wiek

## Korelacja i regresja

<font color='blue'>**Korelacja** </font>. Do obliczania poziomu zależności liniowej między dwiema zmiennymi (X,Y) używamy współczynnika korelacji liniowej Pearsona. Przyjmuje on wartości z zakresu $[-1,1]$. 

$$ r_{xy} = \frac{\sum_{i=1}^{n}(x_i - \overline{X})(y_i - \overline{Y})}{\sqrt{\sum_{i=1}^{n}(x_i - \overline{X})^2(y_i - \overline{Y})^2}} $$

gdzie: $\overline{Y}, \overline{X}$ to średnie wartości zmiennych

Dodatnia wartość r mówi o tym, że wzrostowi jednej cechy odpowiada wzrost średnich wartości drugiej cechy. Wartość ujemna - wzrostowi wartości jednej cechy odpowiada spadek średnich wartości drugiej cechy. Wartość bezwzględna współczynnika korelacji Pearsona mówi o sile zależności. W pythonie można uzyskać macierz korelacji za pomocą ``np.corrcoef(x,y)``, a następnie wyciągnąć interesujący nas element macierzy. Alternatywą jest ``scipy.stats.pearsonr(x,y)`` i pierwszy element (czyli ten o indeksie zerowym) zwracanej krotki

<font color='blue'>**Regresja**</font>

O kształcie zależności mówi nam regresja. Dla cech X i Y, między którymi istnieje liniowa zależność korelacyjna można szacować parametry liniowej funkcji regresji.

Regresja Y względem X:

$$ \hat{y} = a_y x + b_y$$

$Y$ - cecha zależna, objaśniana
$X$ - cecha niezależna, objaśniająca
$a_y$ - współczynnik kierunkowy regresji, określa o ile jednostek przeciętnie zmieni się wartość cechy Y, gdy wartość cechy X wzrośnie o jedną jednostkę.

$$ a_y = \frac{\sum_{i=1}^{n}(x_i - \overline{X})(y_i - \overline{Y})}{\sum_{i=1}^{n}(x_i - \overline{X})^2} $$ 

$ b_y $ - wyraz wolny
$$ b_y = \overline{Y} - a_y \overline{X} $$

Do oceny jakości dopasowania funkcji regresji możemy wykorzystać współczynnik determinacji $R^2$. Przyjmuje on wartości z zakresu $[0,1]$. Wyższe wartości oznaczają dobre dopasowanie. Mówi też on o tym jaka część zmienności zmiennej objaśnianej jest wyjaśniana przez model.

$$ R^2 = r_{xy}^2 = \frac{(\hat{y}_t - \overline{y})^2}{\sum_{i=1}^{n}(y_t - \overline{y})^2}$$

Współczynnik zbieżności $\varphi^2$ przyjmuje wartości z zakresu od $[0,1]$, i w przeciwieństwie do współczynnika determinacji dążymy do jak najmniejszej wartości.

$$ \varphi^2 = 1 - R^2 $$

W pythonie możemy skorzystać z ``scipy.stats.linregress(x,y)``

<font color='red'>**Korelacja i regresja**</font> Chcąc zbadać zależność między ilością emitowanych dziennie w TV reklam pewnego proszku do prania a wysokością obrotów przeprowadzono badanie. Wyniki podano w poniższej tabeli:

|Liczba reklam |	3| 	4| 	5| 	6| 	5| 	7| 
| --- | --- | --- | --- | --- | --- |--- |
|Obroty [tys. zł]| 	12| 13| 16| 18| 15| 22 |

a) Sporządzić wykres rozrzutu. Obliczyć współczynnik korelacji Pearsona. Czy istnieje zależność między ilością reklam a wielkością obrotów? Jeżeli zależność istnieje to jaka jest jej siła? 

b) Wyznaczyć prostą regresji obrotów względem liczby reklam. Podać interpretację parametrów regresji.

c) Wyznaczyć prostą regresji liczby reklam względem obrotów. Podać interpretację parametrów regresji.

d) Jeśli zwiększymy ilość reklam do 8 dziennie, to jakie będą spodziewane obroty? 

e) Otrzymano obroty 17 tys. zł, jaka była przypuszczalna liczba reklam dziennie? 

f) W jakim procencie liczba reklam jest wyjaśniana przez obroty?

g) Obliczyć współczynnik zbieżności. Zinterpretować otrzymany wynik. 

In [ ]:
reklamy = np.array([3, 4, 5, 6, 5, 7])
obroty = np.array([12, 13, 16, 18, 15, 22])

# a) wykres rozrzutu


In [ ]:
# pearson

In [ ]:
# reklamy względem obrotów

In [ ]:
# obroty  względem reklam

In [ ]:
# ile wyniosą obroty, gdy reklamy = 5

In [ ]:
# ile było reklam jeśli obroty wyniosły 17

In [ ]:
# w ilu % jest wyjaśniana zmienności

In [ ]:
# współczynnik zbieżności